version: "3.9"

services:

  # APP LOCAL
  app:
    profiles: ["local"]
    build:
      context: .
      dockerfile: Dockerfile
    image: ci_cd:local
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    depends_on:
      - db


  # DB LOCAL
  db:
    profiles: ["local"]
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql



    
  # APP PROD 
  app-prod:
    profiles: ["prod"]
    image: cockertest-h0fscufthzcgavc8.azurecr.io/ci_cd:${APP_VERSION}
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    depends_on:
      - db-prod

  # DB PROD
  db-prod:
    profiles: ["prod"]
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
